"""
Django settings for production project.

Generated by 'django-admin startproject' using Django 3.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import socket
import pymongo
from pymongo import MongoClient


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
print("BASE_DIR:", BASE_DIR)

# work with local and cloud environment 
CURRENT_ENVIRONMENT = os.environ.get('ENVIRONMENT', 'local')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m43s@rg)pb8%rhy__&t$#8g6%b!==73$^%5c6kwieaaxvum2cl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'


ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'account',
    'frontend',
    'klaen',
    'monitoringapps',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
]


ROOT_URLCONF = 'production.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'production.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.dummy',
    }
}

def is_server():
    hostname = socket.gethostname()
    server_indicators = ["vps", "server", "host", "node"]
    return any(indicator in hostname.lower() for indicator in server_indicators)

if is_server():
    DATABASES['default'] = {
        'ENGINE': 'djongo',
        'NAME': 'server_db',
        'CLIENT': {
            'host': '127.0.0.1',
            'port': 27017,
            'authSource': 'admin',
        }
    }
else:

    client = MongoClient('mongodb://localhost:27017')  # Adjust the URL and port as needed

    try:
        # Ping the MongoDB server
        client.admin.command('ping')  # This command checks if the connection is successful
        print("MongoDB connection successful!")
        DATABASES['default'] = {
            'ENGINE': 'djongo',
            'NAME': 'server_db',
            'CLIENT': {
                'host': '127.0.0.1',
                'port': 27017,
                'authSource': 'admin',
            }
        }
    except Exception as e:
        print(f"No local database detected: {e}. Falling back to SQLite.")
        DATABASES['default'] = {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    
LOGIN_URL = '/account/login/'

# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'server_db',
#         'ENFORCE_SCHEMA': False,
#         'CLIENT': {
#             'host': 'localhost',
#             'port': 27017,  # Use the local port you've chosen for the SSH tunnel
            # 'username': 'your_mongodb_username',
            # 'password': 'your_mongodb_password',
            # 'authSource': 'admin',  # or your database name, if it's different
            # 'authMechanism': 'SCRAM-SHA-1'  # Default mechanism, change if needed
    #     }
    # }
# }


# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'mongodb://10.12.179.2:27017/server_db',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
#adding this command below
STATICFILES_DIRS=(
    # os.path.join(BASE_DIR,'static'),
    BASE_DIR / 'frontend' / 'static',
    # BASE_DIR / "static",
)
# STATIC_ROOT = BASE_DIR / "static"
STATIC_ROOT = BASE_DIR / 'staticfiles'
# STATIC_ROOT = '/var/www/production/frontend/static'



#adding this command below
# STATICFILES_DIRS=(
#     os.path.join(BASE_DIR,'static'),
# )
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_ENGINE = 'django.contrib.sessions.backends.file'
SESSION_FILE_PATH = '/tmp/django_sessions'  # Or any directory where Django can write session files
