# Generated by Django 5.2.6 on 2025-09-26 05:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FCMTOken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'lighting_fcmtoken',
            },
        ),
        migrations.CreateModel(
            name='lightingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'lighting_log',
            },
        ),
        migrations.CreateModel(
            name='OutdoorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('timestamp', models.IntegerField()),
            ],
            options={
                'db_table': 'klaen_outdoorData',
            },
        ),
        migrations.CreateModel(
            name='PlalionSensorCompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ozone', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('dust', models.FloatField()),
                ('co2', models.IntegerField()),
                ('voc', models.IntegerField()),
                ('serial_num', models.CharField(max_length=255)),
                ('last_time', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
                ('m_enable', models.BooleanField()),
                ('s_enable', models.BooleanField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'plalion_company_sensor',
            },
        ),
        migrations.CreateModel(
            name='PlalionSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ozone', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('dust', models.FloatField()),
                ('co2', models.IntegerField()),
                ('voc', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('client_id', models.CharField(max_length=255, null=True)),
                ('client_secret', models.CharField(max_length=255, null=True)),
                ('app_id', models.CharField(max_length=255, null=True)),
                ('device_id', models.CharField(max_length=255, null=True)),
                ('device_name', models.CharField(max_length=255, null=True)),
                ('registration_type', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('ozone', models.FloatField()),
                ('dust', models.FloatField()),
                ('device', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='StoringLighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('lightHue', models.IntegerField()),
                ('lightSat', models.IntegerField()),
                ('lightBri', models.IntegerField()),
                ('lightCT', models.IntegerField()),
                ('lightStatus', models.CharField(max_length=64)),
                ('lightId', models.CharField(max_length=64)),
                ('roomName', models.CharField(max_length=255)),
                ('switchMode', models.CharField(max_length=255)),
                ('deviceTemp', models.FloatField(null=True)),
                ('lightLuminance', models.FloatField(null=True)),
                ('motion', models.CharField(max_length=255, null=True)),
                ('location', models.JSONField()),
                ('device', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'lighting_weatherapi',
            },
        ),
    ]
