# Generated by Django 5.2 on 2025-09-04 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klaen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plalionsensorcompanydata',
            table='plalion_company_sensor',
        ),
    ]
